### ISSUE TITLE
ㅇ

### ISSUE THREAD

**Issue by dlrjs2360** [CAKK-official/CAKK_back#1]
![image](https://user-images.githubusercontent.com/81156109/163665707-d20ae1d6-4fa5-43f7-ab27-21ac00e4f9fa.png)

**Comment by Hyevvy** [comment]
닫을게염

**Comment by sunseo18** [comment]
![277475736_702320147442070_7119069696293008008_n](https://user-images.githubusercontent.com/78674565/164954867-98bb9784-bf65-46f2-8d76-dd0662f1e780.jpeg)

뵈르니
![이단+생황](https://user-images.githubusercontent.com/78674565/179344922-b65726b3-d68b-45ee-80c4-531638d41b99.jpeg)
![피규어](https://user-images.githubusercontent.com/78674565/179345095-ab84c251-8553-4d2d-95b9-66ce41c6f671.jpeg)
![피규어2](https://user-images.githubusercontent.com/78674565/179345208-d236308d-23c8-49b2-8813-cc60193e9427.jpeg)

데이지케이크
<img width="334" alt="레터링" src="https://user-images.githubusercontent.com/78674565/179345447-497f8232-ad7b-412d-9c86-53a8b87c1b46.png">

니어바이스위츠
<img width="334" alt="레터링2" src="https://user-images.githubusercontent.com/78674565/179345554-0339acc5-3c54-4cd3-97bd-96e8805bf753.png">

**Comment by sunseo18** [comment]
![278493227_1180422686028137_5840777734012582906_n](https://user-images.githubusercontent.com/78674565/164955456-0f7d5187-403b-4dda-9854-49e40d90cbef.jpeg)

![입체](https://user-images.githubusercontent.com/78674565/164955547-6baea1b3-78cf-4ae0-a849-a2b2755f8481.jpeg)
![입체2](https://user-images.githubusercontent.com/78674565/164955600-2c56b089-54c8-4016-b621-2a59d938499f.jpeg)
![포토](https://user-images.githubusercontent.com/78674565/164955623-446441c3-fd59-475b-b0a5-f4a50bdf813e.jpeg)
![티아라](https://user-images.githubusercontent.com/78674565/164955684-f84af9b8-107d-4388-b1be-1533ec8fa25f.jpeg)

> 케키하우스

![보틀](https://user-images.githubusercontent.com/78674565/164955758-e5105c8e-e475-46e5-bc4f-c9c763372b7a.jpeg)
![이단 티아라](https://user-images.githubusercontent.com/78674565/164955855-ca1f9b63-59b4-47a3-9020-0e4ab46fe47f.jpeg)

> 디저트진진

![썸네일](https://user-images.githubusercontent.com/78674565/164955910-6068fa24-28ea-4838-b17d-8345956d6e76.jpeg)
![레터링](https://user-images.githubusercontent.com/78674565/164955950-8434eaae-cb53-4ce0-a490-5bafb15da1e9.jpeg)
![입체](https://user-images.githubusercontent.com/78674565/164955961-e0bf789e-f283-4eed-9b5e-8531f9cf679a.jpeg)
![보틀](https://user-images.githubusercontent.com/78674565/164955990-88b996de-f23b-412b-a07b-ba00684fdfb2.jpeg)
![보틀2](https://user-images.githubusercontent.com/78674565/164956014-257153d4-03b2-4b41-94a0-c4c10cd2e549.jpeg)
![입체2](https://user-images.githubusercontent.com/78674565/164956035-f945980f-03b9-4802-997d-ace2481c7484.jpeg)

> 펫어케이크

![썸네일](https://user-images.githubusercontent.com/78674565/164956627-72063095-2ff1-4840-b45b-7d2e6835d152.jpeg)
![꽃](https://user-images.githubusercontent.com/78674565/164956249-dc120952-39b5-484d-9ca5-e54867c26e45.jpeg)
![레터링](https://user-images.githubusercontent.com/78674565/164956265-9c9f145b-9b6b-4c81-af79-d05ca5b
27cbf.jpeg)
![레터링2](https://user-images.githubusercontent.com/78674565/164956283-46b07d9a-4ebf-45f9-888c-953a817f98b1.jpeg)

> 쏘스윗마카롱

![썸네일](https://user-images.githubusercontent.com/78674565/164956648-7e1b1bbb-a585-49c7-ae65-470e32d5bf9f.jpeg)
![티아라](https://user-images.githubusercontent.com/78674565/164956330-0b2afa3b-233d-4ac0-8499-b7e79ebdec30.jpeg)
![보틀](https://user-images.githubusercontent.com/78674565/164956354-38d224e7-fdfb-48c0-b37c-0c51242821bb.jpeg)
![도시락](https://user-images.githubusercontent.com/78674565/164956362-a4e1a2dc-1d55-475e-9a15-126b28c69bf8.jpeg)
![입체](https://user-images.githubusercontent.com/78674565/164956367-3184c80e-b99b-439d-bdd2-c3d8dfbf457e.jpeg)

> 베이커리숲
![썸네일](https://user-images.githubusercontent.com/78674565/164956586-fed6a39f-eab5-4e59-bfeb-eba70d22c0b2.jpeg)
![생화+레터링](https://user-images.githubusercontent.com/78674565/164956445-a6af287e-231f-48c9-b380-65c0c0e9db18.jpeg)
![입체](https://user-images.githubusercontent.com/78674565/164956457-53b8eac5-753d-4aa3-bb40-f1d68b753bad.jpeg)
![도시락](https://user-images.githubusercontent.com/78674565/164956477-30060c7e-c71f-4e49-b4a5-7afc92ff12b8.jpeg)
![생화+도시락](https://user-images.githubusercontent.com/78674565/164956485-abbcc75c-624a-4fcf-9e6c-15f70bf4fbb5.jpeg)
![티아라](https://user-images.githubusercontent.com/78674565/164956529-10e3d380-df6c-4dd9-ac0e-026a0cacb002.jpeg)
![도시락+레터링](https://user-images.githubusercontent.com/78674565/164956530-333b2d0d-becc-48a4-8dd2-4ea1b733097e.jpeg)
![레터링+피규어](https://user-images.githubusercontent.com/78674565/164956532-00d4224a-5186-4727-b04f-449282357d18.jpeg)

> 케이크바이미

![썸네일](https://user-images.githubusercontent.com/78674565/164956750-5047b21b-ca5c-402e-9898-3dd89c13677f.jpeg)
![티아라](https://user-images.githubusercontent.com/78674565/164956670-7513dbc4-b943-4b86-acb9-ed012f709408.jpeg)
![레터링](https://user-images.githubusercontent.com/78674565/164956675-76522bbd-c731-4886-8bab-497b6cb157ce.jpeg)
![하트](https://user-images.githubusercontent.com/78674565/164956695-8e194a7a-c160-44fd-8f6f-9df0bb743357.jpeg)
![하트+레터링](https://user-images.githubusercontent.com/78674565/164956702-69aa8c2e-599a-4f2b-bbbc-0a8234d4bcd8.jpeg)
![티아라2](https://user-images.githubusercontent.com/78674565/164956727-20e8dcf4-1dde-47a5-8408-57bcfcdb861b.jpeg)

> 서커스래빗

![썸네일](https://user-images.githubusercontent.com/78674565/164956882-e08614c7-f40c-439d-bfb5-447d3850a17a.jpeg)
![도시락+레터링](https://user-images.githubusercontent.com/78674565/164956797-718703e7-31f2-4002-a35d-f614a0c485a4.jpeg)
![피규어](https://user-images.githubusercontent.com/78674565/164956809-153a3b0b-7897-4953-a338-18af02a562b9.jpeg)
![생화+레터링](https://user-images.githubusercontent.com/78674565/164956817-e8388551-0cfd-4bb5-9c1d-c6445f15e629.jpeg)
![피규어+레터링](https://user-images.githubusercontent.com/78674565/164956825-92582188-479b-4915-9fd9-73ebb2afffd0.jpeg)
![이단](https://user-images.githubusercontent.com/78674565/164956833-297ffc80-6dd9-410b-9141-ddce304071de.jpeg)

> 나롱스케이크

![썸네일](https://user-images.githubusercontent.com/78674565/164956912-cee21997-f923-4c59-8393-03a38f000989.jpeg)
![이단](https://user-images.githubusercontent.com/78674565/164956920-351fa180-f8ef-4a1b-bc75-c25857ad0af8.jpeg)
![레터링+포토](https://user-images.githubusercontent.com/78674565/164956931-b173d367-505f-42d7-9c17-f50cc2cf307c.jpeg)
![티아라](https://user-images.githubusercontent.com/78674565/164956940-59c6720c-8e88-43a0-ac2f-65a40838a2a0.jpeg)
![레터링](https://user-images.githubusercontent.com/78674565/164956955-cbf2b55b-921e-4c86-9597-b1620090a2b5.jpeg)
![피규어](https://user-images.githubusercontent.com/78674565/164956970-a1bdbcba-ede4-4029-b5ce-1c397bc4d176.jpeg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165950927-4d69ded0-f951-4bad-a58e-15d731a1081c.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165951206-b4673095-b84f-4669-a6fc-7ea89f7173c0.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165951632-4503cced-45c8-4ede-886d-bf138b3de239.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165951711-25d8116c-4d6f-4363-8adc-d1227193a62a.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165951978-03ef0539-1021-4a4b-a67c-b0dccbd8c7c6.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165952618-adb9d807-5699-4576-b481-49387807bf58.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165952724-e7eeef3f-2905-472a-b271-c85a24cbef82.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165952945-aba57c0a-672c-43ba-bfd6-bcc0e9f6816c.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165953160-6e952e5d-8269-4264-9bbb-ab8044fe12e4.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165953261-3ad5ed93-697d-4fb2-a94a-39e4cf87359f.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165953405-dbf31d51-c14b-4c46-91a3-c0b8a9aa2f95.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165953602-e376553b-0a0f-4961-b5d3-67c3efc639b1.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165953762-d12a7391-2466-4aa9-a700-c22616fde39d.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165953948-39763ab4-51dd-4fb5-b6c9-c57cded4c2a5.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165954165-7ebec683-ae3b-4513-a0d1-f115492be87f.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165954263-18130fc3-63d7-4db6-b4aa-ccf0ab2b0a0c.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165954396-e1ff3847-14d2-435c-884f-029e3aede538.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165954541-19268011-e647-4c69-b085-97a1015f65d1.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165954798-d815bbac-f43b-4296-b74c-7b16d2c30a08.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165954961-e812f27e-891a-4352-9516-61b52d8bc971.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165955089-6384f7cb-713a-48f5-a57c-487a5d9e4e5e.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165955245-a9abab8a-2cac-4d23-ba48-7feb65692a97.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165955478-4244c3ae-5e39-42d3-9862-766bc701c8df.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165955659-e5f9613c-902c-4fd2-98a2-4b8783411e6a.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165955900-6fe7d961-750b-480b-9ece-ee247885233b.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165956035-d5c0e3e1-5af8-4768-a807-f0ae1beaecab.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165956174-3e4f69a7-d56a-4905-8004-47976cc581e5.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165956274-a34f384c-c6ec-490b-a0e6-e324c128b591.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165956626-52cb5ed1-cce1-466b-8cd0-abfe1bf33a2d.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165956781-a4bf3491-d728-4be0-87f5-6c0b649bc004.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165956961-131007c7-5650-47fc-8cba-92c55461a4bd.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165957067-220301e5-b5cc-4015-8c26-42eccde8ffd3.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165957425-65a5c174-f486-4d00-a6cb-f1ce3114794f.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165957534-f508819a-a69f-440e-a0d4-1db9a613a21a.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165957608-83f845d8-c468-46f9-871f-e5e661f043f8.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165957805-9ffee4fe-b813-4b6e-a74b-3f775c6d800e.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165957983-d42bfd94-47eb-4617-b799-42b23e5370ed.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165958072-306d14ef-bcae-4f63-9c26-b4bd6ce44727.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165958190-206b29fc-a737-4017-a3e3-259f05029274.jpg)

**Comment by dlrjs2360** [comment]
![download](https://user-images.githubusercontent.com/81156109/165958312-6862527a-39f9-447c-a63e-cc65a4d9408c.jpg)
